#! /bin/bash
#generated by orchestrate.py
source ./util

#configure vswitch:vswitch1
create_netns vswitch1

#configure vswitch:vswitch2
create_netns vswitch2

#configure lan:lan1
create_lan lan1
bind_ipaddr_to_lan lan1 192.168.1.1/24
bind_ipaddr_to_lan lan1 10.0.10.1/24
enable_snat_lan lan1 192.168.1.0/24

#configure lan:lan2
create_lan lan2

#configure interface:eth0
create_link eth0 lan1 vswitch2
bind_ipaddr_to_link eth0 vswitch2 192.168.1.2/24
bind_ipaddr_to_link eth0 vswitch2 10.0.10.2
set_gateway eth0 vswitch2 192.168.1.1

#configure interface:eth1
create_link eth1 lan1 vswitch2
